### ISSUE TITLE
Пропадает перевод главного меню через Epic Games

### ISSUE THREAD

**Issue by anym1re** [Kvasus/BaronyRussianTranslation#1]
Во время загрузки все норм, а вот в главном меню(

![Снимок экрана 2023-09-25 111614](https://github.com/Kvasus/BaronyRussianTranslation/assets/59447145/0741f2d1-01e2-4d20-aebd-290834918bee)
![Снимок экрана 2023-09-25 111646](https://github.com/Kvasus/BaronyRussianTranslation/assets/59447145/7f725a2b-bd7a-4089-ba9b-f86a92e3d420)
![Снимок экрана 2023-09-25 111720](https://github.com/Kvasus/BaronyRussianTranslation/assets/59447145/81568b1a-ad6f-4e30-af2b-ca41182093a6)

**Comment by Kvasus** [comment]
Вышло обновление, в котором добавили строки из главного меню. Прошу прощения, забыл залить сюда.

**Comment by Kvasus** [comment]
Залил новую версию.

**Comment by anym1re** [comment]
Спасибо большое!

**Comment by anym1re** [comment]
> Залил новую версию.

Спасибо большое!
